authapp/urls.py
from django.urls import path

from . import views

app_name = 'authapp'

urlpatterns = [
   path('login', views.login, name='login'),
   path('logout', views.logout, name='logout'),
   path('edit', views.edit, name='edit'),
   path('register', views.register, name='register'),
   path('verify/<email>/<key>', views.verify, name='verify'),
]

cartapp/urls.py
from django.urls import path

import cartapp.views
from . import views

app_name = 'cartapp'

urlpatterns = [
   path('', views.CartTemplateView.as_view(), name='view'),
   path('add/<int:pk>', views.add_to_cart, name='add_to_cart'),
   path('remove/<int:pk>', views.remove_from_cart, name='remove_from_cart'),
   path('api/edit/<int:pk>/<int:quantity>/', views.api_edit_cart, name='edit')

]

geekshop/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from mainapp import views as mainapp_views


urlpatterns = [
    # path('defaultadmin/', admin.site.urls),
    path('', mainapp_views.IndexListView.as_view(), name='index'),
    path('', include('social_django.urls', namespace='social')),
    path('contacts/', mainapp_views.contact, name='contact'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('cart/', include('cartapp.urls', namespace='cart')),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('order/', include('ordersapp.urls', namespace='order')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
   path('', mainapp.ProductsListView.as_view(), name='index'),
   path('category/<int:pk>/', mainapp.ProductsListView.as_view(), name='category'),
   path('product/<int:pk>/', mainapp.ProductDetailView.as_view(), name='product'),
]

mainapp/models.py
from django.db import models
from django.db.models.fields import DecimalField, IntegerField
from django.db.models.fields.related import ForeignKey
import random


class ProductManager(models.Manager):

    @property
    def hot_product(self):
        list_of_products = list(self.filter(is_active=True))
        return random.choice(list_of_products)


class ProductCategory(models.Model):
    name = models.CharField(verbose_name="имя",
                            max_length=64,
                            unique=True)
    description = models.TextField(verbose_name="описание",
                                   blank=True)
    is_active = models.BooleanField(verbose_name="в каталоге", default=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    objects = ProductManager()

    name = models.CharField(verbose_name="имя",
                            max_length=128,
                            unique=True)
    description = models.TextField(verbose_name="описание",
                                   blank=True)
    category = ForeignKey(ProductCategory, on_delete=models.SET_NULL,
                          null=True)
    short_description = models.CharField(verbose_name="короткое описание",
                                         max_length=64,
                                         blank=True)
    price = DecimalField(verbose_name="цена",
                         max_digits=8,
                         decimal_places=2,
                         default=0)
    price_with_discount = DecimalField(verbose_name="цена со скидкой",
                                       max_digits=8,
                                       decimal_places=2,
                                       default=0)
    quantity = IntegerField(verbose_name="кол-во на складе",
                            default=0)
    image = models.ImageField(upload_to="products_images",
                              blank=True)
    is_active = models.BooleanField(verbose_name="в каталоге", default=True)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

adminapp/views/product.py
from django.contrib.auth.decorators import user_passes_test
from django.core.exceptions import PermissionDenied
from mainapp.models import Product
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.utils.decorators import method_decorator


def check_if_superuser(user):
    if not user.is_superuser:
        raise PermissionDenied
    return True


class ProductsListView(ListView):
    model = Product
    template_name = 'adminapp/products.html'
    paginate_by = 2

    def get_queryset(self):
        return Product.objects.filter(category=self.kwargs['pk'])

    @method_decorator(user_passes_test(check_if_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class ProductCreateView(CreateView):
    model = Product
    template_name = 'adminapp/product_update.html'
    success_url = reverse_lazy('admin:categories')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.object = self.get_object()
        context['id'] = self.object.category.id

        return context


class ProductDetailView(DetailView):
    model = Product
    template_name = 'adminapp/product.html'


class ProductUpdateView(UpdateView):
    model = Product
    template_name = 'adminapp/product_update.html'
    success_url = reverse_lazy('admin:categories')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.object = self.get_object()
        context['id'] = self.object.category.id
        return context

    @method_decorator(user_passes_test(check_if_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class ProductDeleteView(DeleteView):
    model = Product
    template_name = 'adminapp/product_delete.html'
    success_url = reverse_lazy('admin:categories')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

mainapp/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from datetime import datetime

from django.views import View
from django.views.generic import TemplateView, DetailView

from .models import ProductCategory, Product
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic.list import ListView

menu_links = [
    {'view_name': 'index', 'active_if': ['index'], 'name': 'домой'},
    {'view_name': 'products:index', 'active_if':
        ['products:index', 'products:category', 'products:product', 'products:page', 'products:hpage'],
     'name': 'продукты'},
    {'view_name': 'contact', 'active_if': ['contact'], 'name': 'контакты'},
]

list_of_products = Product.objects.filter(is_active=True)


class IndexListView(ListView):
    model = Product
    template_name = 'mainapp/index.html'
    paginate_by = 4

    def get_queryset(self):
        return super().get_queryset().filter(is_active=True).order_by("price")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['date_now'] = datetime.now()
        context['container_block_class'] = "slider"
        context['menu_links'] = menu_links
        return context


class ProductDetailView(DetailView):
    model = Product
    template_name = 'mainapp/product.html'

    def get_object(self):
        return get_object_or_404(Product, id=self.kwargs.get('pk'))

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['container_block_class'] = "hero-white"
        data['product_categories'] = ProductCategory.objects.all()
        data['menu_links'] = menu_links
        return data


class ProductsListView(ListView):
    template_name = 'mainapp/products.html'
    model = Product
    paginate_by = 3

    def get_queryset(self):
        queryset = super().get_queryset()
        category_pk = self.kwargs.get('pk')
        if category_pk:
            queryset = queryset.filter(category__pk=category_pk)
        return queryset

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        category_pk = self.kwargs.get('pk')
        data['container_block_class'] = "hero-white"
        data['product_categories'] = ProductCategory.objects.all()
        data['menu_links'] = menu_links
        data['hot_product'] = Product.objects.hot_product
        data['category_pk'] = category_pk

        return data


def contact(request):
    return render(request, 'mainapp/contact.html', context={'menu_links': menu_links,
                                                            'title': 'наши контакты',
                                                            'container_block_class': "hero",
                                                            })

mainapp/templates/mainapp/base.html
{% load static %}


<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Магазин</title>
	<link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href= "{% static 'style.css' %}" >
    {% block js %}
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% endblock %}
</head>
<body>
	<div class="container">
        <div class="{{ container_block_class }}">
            {% include 'mainapp/include/inc_menu.html' %}
            {% block title %}
            {% endblock %}
        </div>
        {% block 'content' %}
        {% endblock %}

    </div>
    <div class="footer">
        {% include 'mainapp/include/inc_footer.html' %}
    </div>


</body>
</html>

mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load static %}
	{% block title %}
	<h1> {{ title|title }} </h1>
	{% endblock %}
{% block 'content'%}

<div class="location">
	<div class="location-1">
		<i class="fa fa-map-marker fa-5x"></i>
		<h4>Москва</h4>
		<div class="contacts">
			<h5>Телефон</h5>
			<p>+7-888-888-8888</p>
		</div>
		<div class="contacts">
			<h5>Email</h5>
			<p>info@geekshop.ru</p>
		</div>
		<div class="contacts">
			<h5>Адрес</h5>
			<p>В пределах МКАД</p>
		</div>
	</div>
	<div class="location-1">
		<i class="fa fa-map-marker fa-5x"></i>
		<h4>Москва</h4>
		<div class="contacts">
			<h5>Телефон</h5>
			<p>+7-888-888-8888</p>
		</div>
		<div class="contacts">
			<h5>Email</h5>
			<p>info@geekshop.ru</p>
		</div>
		<div class="contacts">
			<h5>Адрес</h5>
			<p>В пределах МКАД</p>
		</div>
	</div>
	<div class="location-1">
		<i class="fa fa-map-marker fa-5x"></i>
		<h4>Москва</h4>
		<div class="contacts">
			<h5>Телефон</h5>
			<p>+7-888-888-8888</p>
		</div>
		<div class="contacts">
			<h5>Email</h5>
			<p>info@geekshop.ru</p>
		</div>
		<div class="contacts">
			<h5>Адрес</h5>
			<p>В пределах МКАД</p>
		</div>
	</div>
</div>

<div class="clr"></div>

{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load my_tags %}

	{%block title%}
	<div class="text-slider">
		<h3 class="green">тенденции {{ date_now|date:"Y" }}</h3>
		<h3 class="big"> удобные стулья</h3>
		<p>Новый уровень комфорта в {%now "Y"%}. Отличные характеристики.</p>
		<a href="#" class="button-order">заказать <img src="{% static 'img/arrow.png' %}" alt=""></a>
	</div>
	<div class="navi">
		<a href="#"></a><a href="#"></a><a href="#"></a>
	</div>
	{% endblock %}

{% block 'content' %}
	<div class="featured">
		<div class="featured-menu">
			{% block pagination %}
			  {% if is_paginated %}
					  <span class="page-links">
						  {% if page_obj.has_previous %}
							  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">назад</a>
						  {% endif %}
						  <span class="page-current">
							  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
						  </span>
						  {% if page_obj.has_next %}
							  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">вперед</a>
						  {% endif %}
					  </span>
			  {% endif %}
			{% endblock %}
		</div>

		<div class="clearfix">
		</div>
		<div class="tab-content">
			{% for object in object_list %}
			<div class="block">
				<a href="{% url 'products:product' object.id %}"><img src="{{ object.image|media_folder_products }}" class="block" alt="">
					<div class="text">
						<img src="{% static 'img/icon-hover.png' %}" alt="">
						<h3>{{ object.category.name }}</h3>
						<h4>{{ object.name }}</h4>
						<p>{{ object.description }}</p>
					</div>
				</a>
			</div>
			{% endfor %}
		</div>
	</div>

<div class="clr">

</div>
{% endblock %}

mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block 'content' %}
<div class="details">
	{% include 'mainapp/include/inc_submenu.html' %}
	<div class="details-products">
        <div class="details-slider">
            <div class="slider-product">
                <img class="details-slider" src="{{ object.image|media_folder_products }}">
            </div>
        </div>

        <div class="description">
            <h3 class="big-bold">{{ object.short_description }} </h3>
            <h3 class="red">горячее предложение</h3>
            <p class="price"> {{ object.price_with_discount }} <span>руб</span></p>
            <a href="{% url 'cart:add_to_cart' object.id %}" class="red-button">
                заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
            </a>
            <div class="description-text">
                <p>{{ object.name }}</p>
                <p>{{ object.description }}</p>
                <p>Отличное качество материалов </p>
                <p>высочайший уровень
                эргономики и прочность.</p>
            </div>
        </div>
    </div>

</div>
<div class="clr"></div>
{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block 'content' %}
<div class="details">
	{% include 'mainapp/include/inc_submenu.html' %}
	{% if request.resolver_match.url_name == 'index'%}
		{% include 'mainapp/include/inc_hot_product.html' %}
	{% elif request.resolver_match.url_name == 'category'%}

	<div class="details-products">
		<div class="details-slider">
			<div class="slider-product">
				<img src="{{ object_list.0.image|media_folder_products }}" class="slider-product">
			</div>
		</div>

		<div class="description">
			<h3 class="big-bold">{{ object_list.0.short_description }}</h3>
			<h3 class="red">горячее предложение</h3>
			<p class="price"> {{ object_list.0.price_with_discount }} <span>руб</span></p>
			<a href="{% url 'products:product' object_list.0.pk %}" class="red-button">
				перейти на страницу <i class="fa fa-chevron-right" aria-hidden="true"></i>
			</a>
			<div class="description-text">
				<p>{{ object_list.0.name }}</p>
				<p>{{ object_list.0.description }}</p>
			</div>
		</div>
	</div>
	{% endif %}
	<div class="related">
		<div class="title clearfix">
			<h2>Похожие продукты</h2>
		</div>
		<div class="related">
			{% block pagination %}
			  {% if is_paginated %}
					  <span class="page-links">
						  {% if page_obj.has_previous %}
							  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">назад</a>
						  {% endif %}
						  <span class="page-current">
							  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
						  </span>
						  {% if page_obj.has_next %}
							  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">вперед</a>
						  {% endif %}
					  </span>
			  {% endif %}
			{% endblock %}
			</div>
		<div class="tab-content">
			{% for item in object_list %}
				<div class="block">
					<a href="{% url 'products:product' item.id %}" ><img src="{{ item.image|media_folder_products }}" class="block" style = "height: 370px; width: 370px" alt="">
						<div class="text" style = "height: 370px; width: 370px">
							<img src="{% static 'img/icon-hover.png' %}"  alt="img">
							<h4>{{ item.category }}</h4>
							<p>{{ item.name }} </p>
							<p>{{ item.description }} </p>
						</div>
					</a>
				</div>
			{% endfor %}

		</div>
	</div>

</div>
<div class="clr" ></div>
{% endblock %}