adminapp/urls.py
from adminapp.views import category, user, product
from django.urls import path

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', user.UsersCreateView.as_view(), name='user_create'),
    path('users/read/', user.UsersListView.as_view(), name='users'),
    path('users/update/<int:pk>/', user.UsersUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', user.UsersDeleteView.as_view(), name='user_delete'),

    path('categories/create/', category.CategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', category.CategoriesListView.as_view(), name='categories'),
    path('categories/update/<int:pk>/', category.CategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', category.CategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', product.ProductCreateView.as_view(), name='product_create'),
    path('products/read/category/<int:pk>/', product.ProductsListView.as_view(), name='products'),
    path('products/read/<int:pk>/', product.ProductDetailView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', product.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', product.ProductDeleteView.as_view(), name='product_delete'),
]

authapp/urls.py
from django.urls import path

from . import views

app_name = 'authapp'

urlpatterns = [
   path('login', views.login, name='login'),
   path('logout', views.logout, name='logout'),
   path('edit', views.edit, name='edit'),
   path('register', views.register, name='register'),
   path('verify/<email>/<key>', views.verify, name='verify'),
]

cartapp/urls.py
from django.urls import path

import cartapp.views
from . import views

app_name = 'cartapp'

urlpatterns = [
   path('', views.CartTemplateView.as_view(), name='view'),
   path('add/<int:pk>', views.add_to_cart, name='add_to_cart'),
   path('remove/<int:pk>', views.remove_from_cart, name='remove_from_cart'),
   path('api/edit/<int:pk>/<int:quantity>/', views.api_edit_cart, name='edit')

]

geekshop/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from mainapp import views as mainapp_views


urlpatterns = [
    # path('defaultadmin/', admin.site.urls),
    path('', mainapp_views.IndexListView.as_view(), name='index'),
    path('', include('social_django.urls', namespace='social')),
    path('contacts/', mainapp_views.contact, name='contact'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('cart/', include('cartapp.urls', namespace='cart')),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('order/', include('ordersapp.urls', namespace='order')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
   path('', mainapp.ProductsListView.as_view(), name='index'),
   path('category/<int:pk>/', mainapp.ProductsListView.as_view(), name='category'),
   path('product/<int:pk>/', mainapp.ProductDetailView.as_view(), name='product'),
]

ordersapp/urls.py
from django.urls import path

from . import views

app_name = 'ordersapp'

urlpatterns = [
   path('', views.OrderList.as_view(), name='list'),
   path('forming/complete/<pk>', views.order_forming_complete, name='order_forming_complete'),
   path('create/', views.OrderItemsCreate.as_view(), name='create'),
   path('read/<pk>/', views.OrderRead.as_view(), name='read'),
   path('update/<pk>/', views.OrderItemsUpdate.as_view(), name='update'),
   path('delete/<pk>/', views.OrderDelete.as_view(), name='delete'),
   path('product/price/<int:pk>/', views.get_product_price, name='get_product_price'),

]

mainapp/models.py
from django.db import models
from django.db.models.fields import DecimalField, IntegerField
from django.db.models.fields.related import ForeignKey
import random


class ProductManager(models.Manager):

    @property
    def hot_product(self):
        list_of_products = list(self.filter(is_active=True))
        return random.choice(list_of_products)


class ProductCategory(models.Model):
    name = models.CharField(verbose_name="имя",
                            max_length=64,
                            unique=True)
    description = models.TextField(verbose_name="описание",
                                   blank=True)
    is_active = models.BooleanField(verbose_name="в каталоге", default=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    objects = ProductManager()

    name = models.CharField(verbose_name="имя",
                            max_length=128,
                            unique=True)
    description = models.TextField(verbose_name="описание",
                                   blank=True)
    category = ForeignKey(ProductCategory, on_delete=models.SET_NULL,
                          null=True)
    short_description = models.CharField(verbose_name="короткое описание",
                                         max_length=64,
                                         blank=True)
    price = DecimalField(verbose_name="цена",
                         max_digits=8,
                         decimal_places=2,
                         default=0)
    price_with_discount = DecimalField(verbose_name="цена со скидкой",
                                       max_digits=8,
                                       decimal_places=2,
                                       default=0)
    quantity = IntegerField(verbose_name="кол-во на складе",
                            default=0)
    image = models.ImageField(upload_to="products_images",
                              blank=True)
    is_active = models.BooleanField(verbose_name="в каталоге", default=True)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

mainapp/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from datetime import datetime

from django.views import View
from django.views.generic import TemplateView, DetailView

from .models import ProductCategory, Product
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic.list import ListView

menu_links = [
    {'view_name': 'index', 'active_if': ['index'], 'name': 'домой'},
    {'view_name': 'products:index', 'active_if':
        ['products:index', 'products:category', 'products:product', 'products:page', 'products:hpage'],
     'name': 'продукты'},
    {'view_name': 'contact', 'active_if': ['contact'], 'name': 'контакты'},
]

list_of_products = Product.objects.filter(is_active=True)


class IndexListView(ListView):
    model = Product
    template_name = 'mainapp/index.html'
    paginate_by = 4

    def get_queryset(self):
        return super().get_queryset().filter(is_active=True).order_by("price")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['date_now'] = datetime.now()
        context['container_block_class'] = "slider"
        context['menu_links'] = menu_links
        return context


class ProductDetailView(DetailView):
    model = Product
    template_name = 'mainapp/product.html'

    def get_object(self):
        return get_object_or_404(Product, id=self.kwargs.get('pk'))

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['container_block_class'] = "hero-white"
        data['product_categories'] = ProductCategory.objects.all()
        data['menu_links'] = menu_links
        return data


class ProductsListView(ListView):
    template_name = 'mainapp/products.html'
    model = Product
    paginate_by = 3

    def get_queryset(self):
        queryset = super().get_queryset()
        category_pk = self.kwargs.get('pk')
        if category_pk:
            queryset = queryset.filter(category__pk=category_pk)
        return queryset

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        category_pk = self.kwargs.get('pk')
        data['container_block_class'] = "hero-white"
        data['product_categories'] = ProductCategory.objects.all()
        data['menu_links'] = menu_links
        data['hot_product'] = Product.objects.hot_product
        data['category_pk'] = category_pk

        return data


def contact(request):
    return render(request, 'mainapp/contact.html', context={'menu_links': menu_links,
                                                            'title': 'наши контакты',
                                                            'container_block_class': "hero",
                                                            })

mainapp/templates/mainapp/include/inc_footer.html
<div class="clearfix">
    <div class="text-footer">
        <h3>контакты</h3>
    </div>
    <div class="text-footer">
        <h3>полезная информация</h3>
    </div>
    <div class="text-footer clearfix">
        <h3>Оставайтесь на связи</h3>
        <p>Подписаться на новости и рассылки</p>
        <form>
            <input type="email" name="email" placeholder="ваш email">
            <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
        </form>
    </div>
</div>
<p class="small">&copy; GB {%now "Y"%}</p>
<div class="social">
    <a href="#" class="social1"></a>
    <a href="#" class="social2"></a>
    <a href="#" class="social3"></a>
    <a href="#" class="social4"></a>
</div>
<p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>

mainapp/templates/mainapp/include/inc_hot_product.html
{% load static %}
{% load my_tags %}
<div class="details-products">
	<div class="details-slider">
		<div class="slider-product">
			<img class="details-slider" src="{{ hot_product.image|media_folder_products }}">
		</div>

	</div>

	<div class="description">
		<h3 class="big-bold">{{ hot_product.short_description }}</h3>
		<h3 class="red">горячее предложение</h3>
		<p class="price"> {{ hot_product.price_with_discount }} <span>руб</span></p>
		<a href="{% url 'products:product' hot_product.id %}" class="red-button">
			перейти на страницу <i class="fa fa-chevron-right" aria-hidden="true"></i>
		</a>
		<div class="description-text">
			<p>{{ hot_product.name }}</p>
			<p>{{ hot_product.description }}</p>
			<p>Отличное качество материалов </p>
			<p>высочайший уровень
			эргономики и прочность.</p>
		</div>
	</div>
</div>

mainapp/templates/mainapp/include/inc_menu.html
<div class="header clearfix">

    <a href="{% url 'index' %}" class="logo"></a>
    <ul class="menu">
        {% for link in menu_links %}
        <li><a href="{% url link.view_name %}"
               {% if request.resolver_match.view_name in link.active_if %}
               class="active" {% endif %}
        >{{ link.name }}</a></li>
        {% endfor %}
        {% if user.is_authenticated %}
        <li>
           <div class="dropdown">
               <a class="dropdown-toggle" href="" data-toggle="dropdown">
                   {{ user.first_name|default:'Пользователь' }}
                   <span class="caret"></span>
               </a>
               <ul class="dropdown-menu">
                   <li>
                       <a href="{% url 'auth:edit' %}">
                           профиль
                       </a>
                   </li>
                   <li>
                       <a href="{% url 'ordersapp:list' %}">
                           заказы
                       </a>
                   </li>
                   <li>
                       <a href="{% url 'auth:logout' %}">
                           выйти
                       </a>
                   </li>
               </ul>
           </div>
        </li>
        {% else %}
        <li>
            <a href="{% url 'auth:login' %}">войти</a>
        </li>
        <li>
              <a href="{% url 'auth:register' %}">зарегистрироваться</a>
        </li>
        {% endif %}
        {% if user.is_superuser %}
            <li>
              <a href="{% url 'adminapp:categories' %}">админка</a>
            </li>
        {% endif %}
        <li>
            <a href="{% url 'cart:view' %}"> Корзина
        {% if request.user.cart.has_items %}
                ({{ request.user.cart.amount }}шт, {{request.user.cart.total_cost}}р)
        {% endif %}</a>
        </li>

     </ul>

    <a href="#" class="search"></a>
</div>

mainapp/templates/mainapp/include/inc_products_content.html
{% load static %}
{% load my_tags %}
{% block other_js %}
<script src="{% static 'js/main_scripts.js' %}"></script>
{% endblock %}

{% if request.resolver_match.url_name == 'index'%}
    {% include 'mainapp/include/inc_hot_product.html' %}
{% else %}

<div class="details-products">
    <div class="details-slider">
        <div class="slider-product">
            <img src="{{ object_list.0.image|media_folder_products }}" class="slider-product">
        </div>
    </div>
    <div class="description">
        <h3 class="big-bold">{{ object_list.0.short_description }}</h3>
        <h3 class="red">горячее предложение</h3>
        <p class="price"> {{ object_list.0.price_with_discount }} <span>руб</span></p>
        <a href="{% url 'products:product' object_list.0.pk %}" class="red-button">
            перейти на страницу <i class="fa fa-chevron-right" aria-hidden="true"></i>
        </a>
        <div class="description-text">
            <p>{{ object_list.0.name }}</p>
            <p>{{ object_list.0.description }}</p>
        </div>
    </div>
</div>
{% endif %}
<div class="related">
    <div class="title clearfix">
        <h2>Похожие продукты</h2>
    </div>
    <div class="related">
        {% block pagination %}
          {% if is_paginated %}
                  <span class="page-links">
                      {% if page_obj.has_previous %}
                          <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">назад</a>
                      {% endif %}
                      <span class="page-current">
                          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                      </span>
                      {% if page_obj.has_next %}
                          <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">вперед</a>
                      {% endif %}
                  </span>
          {% endif %}
        {% endblock %}
        </div>
    <div class="tab-content">
        {% for item in object_list %}
            <div class="block">
                <a href="{% url 'products:product' item.id %}" ><img src="{{ item.image|media_folder_products }}" class="block" style = "height: 370px; width: 370px" alt="">
                    <div class="text" style = "height: 370px; width: 370px">
                        <img src="{% static 'img/icon-hover.png' %}"  alt="img">
                        <h4>{{ item.category }}</h4>
                        <p>{{ item.name }} </p>
                        <p>{{ item.description }} </p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>

mainapp/templates/mainapp/include/inc_submenu.html
<div class="links clearfix">
    <ul class="links-menu">
        <li>
            <a href="{% url 'products:index'%}" class ={% if request.resolver_match.view_name == "products:index" %} active {% endif %}> ВСЕ
            </a>
        </li>

        {% for category in product_categories %}
        {% if category.is_active %}
        <li>
            <a href="{% url 'products:category' category.id %}"
               class ={% if request.resolver_match.view_name != "products:index" and category.id == category_pk %} active {% endif %}>
            {{ category.name }}
            </a>
        </li>
        {% endif %}
        {% endfor %}
    </ul>
</div>